// eslint-disable-next-line import/no-anonymous-default-export
export default {
    cmr: {
        cmr_id :'',
        remarks :'',
        date_of_document:'',
        sender_id:'',
        sender_name:'',
        sender_language_code:'',
        sender_tax_id:'',
        sender_tax_type_code:'',
        sender_person_name:'',
        sender_complete_number:'',
        sender_email:'',
        sender_postcode:'',
        sender_street_name:'',
        sender_city_name:'',
        sender_country_code:'',
        sender_country_subdivision_name:'',
        documentsAttached: [
            {"NR": 1}
        ],
        consignment: [
            {"NR": 1}
        ],
        },

    invoice: {
        tradeLineItems: [
            {"NR": 1}
        ],
        invoice_id:'',
        date_of_document:'',
        seller_id:'',
        seller_name:'',
        seller_language_code:'',
        seller_tax_id:'',
        seller_tax_type_code:'',
        seller_person_name:'',
        seller_complete_number:'',
        seller_email:'',
        seller_postcode:'',
        seller_street_name:'',
        seller_city_name:'',
        seller_country_code:'',
        seller_country_subdivision_name:'',
        buyer_id:'',
        buyer_name:'',
        buyer_language_code:'',
        buyer_tax_id:'',
        buyer_tax_type_code:'',
        buyer_person_name:'',
        buyer_complete_number:'',
        buyer_email:'',
        buyer_postcode:'',
        buyer_street_name:'',
        buyer_city_name:'',
        buyer_country_code:'',
        buyer_country_subdivision_name:'',
        gross_weight:'',
        net_weight:'',
        package_quantity:'',
        transport_means_id:'',
        occurrence_date_time:'',
        due_payable_amount:'',
        invoice_currency_code:'',
        ibanID:'',
        account_name:'',
        exemption_reason_code:'',
        payment_term_description:'',
    },
}
